sudo: false

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
    - libgmp-dev

install:
  - ./travis_long stack --no-terminal --skip-ghc-check setup --ghcjs-boot-options -j --ghcjs-boot-options 2 --no-ghcjs-boot-clean
  - ./travis_long stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/.ghcjs
  - $HOME/.ghc
  - $HOME/.cabal
